config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/vacations', to: 'users/vacations#index', as: :vacations
  get '/dashboard', to: 'users#show', as: :dashboard

  get '/oauth', to: 'users/dwollas#create', as: :users_auth

  namespace :users do
    resources :dwollas, only: [:create, :new]
    resources :funding_sources, only: [:new]
    resources :vacations, only: [:create, :new, :show, :index] do
      resources :activities, only: [:show, :new, :create]
    end
    resources :activities, only: [] do
      resources :user_activities, only: [:create, :destroy]
    end
  end

  get '/update_funding_source', to: 'users#update'

  resources :vacations do
    namespace :owner do
      resources :activities do
        member {patch :remove}
      end
    end

  post '/transfer', to: 'users/dwollas#transfer', as: :dwollas_transfer
  end

  resources :users, only: [:new, :create, :update]

  namespace :owner do
    resources :vacations, only: [:show] do
      get '/invite', to: 'invitations#new'
      post '/invite', to: 'invitations#create'
    end
    resources :activities, only: [] do
      member {patch :mass_invite}
      resources :user_activities, only: [:create, :new]
    end
  end

  get '/vacation/:id/messages', to: 'messages#index', as: :vacation_messages
  post '/vacation/:id/messages', to: 'messages#create'
  # resources :messages, only: [:index, :create]

  mount ActionCable.server, at: '/cable'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :vacation
  validates :content, presence: true
  scope :for_display, -> { order(:created_at).last(50) }

  def mentions
    content.scan(/@(#{User::NAME_REGEX})/).flatten.map do |username|
      User.find_by(first_name: username)
    end.compact
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :get_messages

  def index
    @vacation = Vacation.find(params[:id])
  end

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'room_channel',
                                    content: message.content,
                                    username: message.user.first_name
                                    
      message.mentions.each do |mention|
        ActionCable.server.broadcast "room_channel_user_#{mention.id}",
                                     mention: true
      end
    end
  end

  private

  def get_messages
    @messages = Message.for_display
    @message = current_user.messages.build
  end

  def message_params
    params.require(:message).permit(:content).merge(vacation_id: params[:id])
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def markdown_to_html(text)
    Kramdown::Document.new(text, input: 'GFM').to_html
  end
end

app/views/messages/_message.html.erb
<div class="message">
  <div class="message-user">
    <%= message.user.first_name %>:
  </div>
  <div class="message-content">
    <%= sanitize markdown_to_html(message.content) %>
  </div>
</div>

app/views/messages/_message_form.html.erb
<div class="message-input">
  <%= form_for([@vacation, @message], remote: true, :url => vacation_messages_path(@vacation)) do |f| %>
    <%= f.text_area :content %>
    <%= f.submit "Send" %>
  <% end %>
</div>

app/views/messages/_messages.html.erb
<div id="messages" class="messages">
  <div id="messages-table" class="messages-table">
    <% if @messages.any? %>
      <% @messages = @messages.select do |message| %>
        <% message.vacation_id == @vacation.id %>
      <% end %>
      <%= render @messages %>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<body class="bg" id="form">
  <div class="activity-container">
    <% if @vacation.host == current_user %>
      <h1 class="dark"><%= link_to @vacation.name, owner_vacation_path(@vacation) %> Chat</h1>
    <% else %>
    <h1 class="dark"><%= link_to @vacation.name, users_vacation_path(@vacation) %> Chat</h1>
    <% end %>
    <div class="message-wr">
      <%= render 'messages' %>
      <%= render 'message_form' %>
    </div>
  </div>
</body>