config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/vacations', to: 'users/vacations#index', as: :vacations
  get '/dashboard', to: 'users#show', as: :dashboard

  get '/oauth', to: 'users/dwollas#create', as: :users_auth

  namespace :users do
    resources :dwollas, only: [:create, :new]
    resources :funding_sources, only: [:new]
    resources :vacations, only: [:create, :new, :show, :index] do
      resources :activities, only: [:show, :new, :create]
    end
    resources :activities, only: [] do
      resources :user_activities, only: [:create, :destroy]
    end
  end

  get '/update_funding_source', to: 'users#update'

  resources :vacations do
    namespace :owner do
      resources :activities do
        member {patch :remove}
      end
    end

  post '/transfer', to: 'users/dwollas#transfer', as: :dwollas_transfer
  end

  resources :users, only: [:new, :create, :update]

  namespace :owner do
    resources :vacations, only: [:show] do
      get '/invite', to: 'invitations#new'
      post '/invite', to: 'invitations#create'
    end
    resources :activities, only: [] do
      member {patch :mass_invite}
      resources :user_activities, only: [:create, :new]
    end
  end

  get '/vacation/:id/messages', to: 'messages#index', as: :vacation_messages
  post '/vacation/:id/messages', to: 'messages#create'
  # resources :messages, only: [:index, :create]

  mount ActionCable.server, at: '/cable'
end

app/models/vacation.rb
class Vacation < ApplicationRecord
  has_many :activities
  has_many :vacation_users
  has_many :users, through: :vacation_users
  has_many :messages

  validates_presence_of :name,
                        :city,
                        :state,
                        :country,
                        :start_date,
                        :end_date

  def host
    vacation_user = self.vacation_users.where(role: 1)[0]
    User.find(vacation_user.user_id)
  end

  def new_vacation?
    self.activities.count == 0
  end

  def calculate_balance(user)
    find_activities(user)
    .where(user_id: user.id)
    .where.not('activities.user_id' => user.id)
    .sum(:price)
  end

  def find_activities(user)
    UserActivity
    .joins(:activity)
    .where(paid: false)
    .where('activities.vacation_id' => self.id)
  end

  def calculate_owed_balance(user)
    find_activities(user)
    .where('activities.user_id' => user.id)
    .sum(:price)
  end

  def owner?(user)
    self.vacation_users.any? do |vu|
      vu.user_id == user.id && vu.vacation_id == self.id && vu.role == 1
    end
  end
end

app/controllers/owner/activities_controller.rb
class Owner::ActivitiesController < ApplicationController

  def index

  end

  def show
    render locals: {
      facade: OwnerActivityFacade.new(params[:id])
    }
  end

  def new
    @vacation = Vacation.find(params[:vacation_id])
    @activity = Activity.new
  end

  def create
   @vacation = Vacation.find(params[:vacation_id])
   @activity = @vacation.activities.new(activity_params)
   if @activity.no_of_days > 1
     create_multi_day(activity_params)
   else
     if @activity.save
       UserActivity.create(user_id: current_user.id, quantity: 1, price: @activity.price_calculation, paid: true, activity_id: @activity.id)
       if @vacation.host == current_user
         redirect_to owner_vacation_path(@vacation)
       else
         redirect_to users_vacation_path(@vacation)
       end
     else
       render :new
     end
   end
 end

 def create_multi_day(activity_params)
   day_count = 1
   no_of_days = activity_params["no_of_days"].to_i
   daily_price = activity_params["price"].to_i / no_of_days
   no_of_days.times do
     activity = Activity.new(activity_params)
     activity.name = "#{activity.name} Day #{no_of_days}"
     activity.price = daily_price
     no_of_days -= 1
     if activity.save
       UserActivity.create(user_id: current_user.id, quantity: 1, price: activity.price_calculation, paid: true, activity_id: activity.id)
     end
   end
   if @vacation.host == current_user
     redirect_to owner_vacation_path(@vacation)
   else @vacation.host != current_user
     redirect_to users_vacation_path(@vacation)
   end
 end

  def mass_invite
    ids = mass_invite_activity.user_activities.pluck(:user_id)
    Vacation.find(params[:id]).users.where.not(id: ids).distinct.each do |user|
      mass_invite_activity.increment!(:num_attendees)
      UserActivity.create(user_id: user.id, quantity: 1, price: mass_invite_activity.price_calculation, paid: false, activity_id: mass_invite_activity.id)
      mass_invite_activity.user_activities.each do |ua|
        ua.price = mass_invite_activity.price_calculation
      end
    end
    if Vacation.find(params[:id]).host.id == current_user.id
      redirect_to owner_vacation_path(Vacation.find(params[:id]))
    else
      redirect_to users_vacation_path(Vacation.find(params[:id]))
    end
  end

  def edit
    @vacation = Vacation.find(params[:vacation_id])
    @activity = associated_activity
  end

  def update
    stale_price_param = associated_activity.price
    associated_activity.update(update_params)
    if price_change?(stale_price_param)
      UserActivity.where(activity_id: associated_activity.id).each do |user_activity|
        user_activity.update_attributes(price: associated_activity.price_calculation)
      end
    end
    redirect_to users_vacation_activity_path(associated_activity.vacation, associated_activity)
  end

  def destroy
    UserActivity.where(activity_id: associated_activity.id).destroy_all
    associated_activity.destroy
    redirect_to users_vacation_path(associated_activity.vacation)
  end

  def remove
    associated_activity.decrement!(:num_attendees)
    user_activity = UserActivity.where(activity_id: associated_activity.id).find_by(user_id: params[:user_id])
    user_activity.delete
    if vacation_owner?
      redirect_to owner_vacation_path(associated_activity.vacation)
    else
      redirect_to vacation_owner_activity_path(associated_activity.vacation, associated_activity)
    end
  end

  private

  def activity_params
    params.require(:activity)
          .permit([:name,
                  :description,
                  :street,
                  :city,
                  :state,
                  :postal_code,
                  :country,
                  :price,
                  :cutoff_date,
                  :no_of_days,
                  :type])
            .merge(user_id: current_user.id,
                  vacation_id: @vacation.id)
  end

  def update_params
    if params.has_key?(:fixed_cost)
      params[:client] = params.delete(:fixed_cost)
    elsif params.has_key?(:per_person_cost)
      params[:client] = params.delete(:per_person_cost)
    end
    params.require(:client).permit([:name, :description, :price, :cutoff_date, :no_of_days, :type])
  end

  def associated_activity
    @_activity ||= Activity.find(params[:id])
  end

  def mass_invite_activity
    @_mass_invite_activity ||= Activity.find(params[:activity_id])
  end

  def price_change?(stale_price_param)
    stale_price_param != update_params[:price]
  end

end

app/controllers/owner/invitations_controller.rb
class Owner::InvitationsController < ApplicationController

  def new
    @vacation = Vacation.find(params[:vacation_id])
  end

  def create
    owner = current_user
    vacation = Vacation.find(params[:vacation_id])
    emails = params[:email_invitations].split(',').map { |email| email.gsub(" ", "") }
    non_existing_users = User.check_for_existing_users(owner, emails, vacation.id)
    non_existing_users.each do |email|
      VacayInviterMailer.invite(owner, email, vacation).deliver_now
    end
    flash[:notice] = 'Successfully sent invitations!'
    redirect_to owner_vacation_path(vacation.id)
  end

end

app/controllers/owner/user_activities_controller.rb
class Owner::UserActivitiesController < ApplicationController

  def show
  end

  def index
  end

  def create
    params[:user_ids].each do |user_id|
      associated_activity.increment!(:num_attendees)
      UserActivity.create(user_id: user_id, quantity: 1, price: associated_activity.price_calculation, paid: false, activity_id: associated_activity.id)
    end
    if associated_activity.vacation.vacation_users.where(role: 1)[0].user_id == current_user.id || associated_activity.user_id == current_user.id
      redirect_to vacation_owner_activity_path(associated_activity.vacation, associated_activity)
    else
      redirect_to users_vacation_activity_path(associated_activity.vacation, associated_activity)
    end
  end

  def new
    ids = associated_activity.user_activities.pluck(:user_id)
    render locals: {
      vacationers: associated_activity.vacation.users.where.not(id: ids),
      activity: associated_activity
    }
  end

  private

  def associated_activity
    Activity.find(params[:activity_id])
  end

end

app/controllers/owner/vacations_controller.rb
class Owner::VacationsController < ApplicationController

  def show
    if Vacation.find(params[:id]).host == current_user
      destination = Vacation.find(params[:id])
      # @locations = [[destination.city, destination.latitude, destination.longitude]]
      # @key = ENV['google_key']
      render locals: {
        facade: VacationsFacade.new(params[:id])
      }
    else render file: "#{Rails.root}/public/404.html" , status: 404
    end
  end

end

app/controllers/users/vacations_controller.rb
class Users::VacationsController < ApplicationController

  def index

  end

  def show
    destination = Vacation.find(params[:id])
    # @locations = [[destination.city, destination.latitude, destination.longitude]]
    # @key = ENV['google_key']
    render locals: {
      facade: VacationsFacade.new(params[:id])
    }
  end

  def new
    @vacation = Vacation.new
  end

  def create
    @vacation = Vacation.new(vacation_params)
    if @vacation.save
      current_user.vacation_users.create(role: 1, vacation: @vacation)
      flash[:success] = "#{@vacation.name} has been created!"
      redirect_to owner_vacation_path(@vacation)
    else
      render :new
    end
  end


  private

  def initial_params
    params.require(:vacation).permit(:name, :city, :state, :country, :start_date, :end_date)
  end

  def vacation_params
    vacation_params = {}
    # coordinates = GeoFacade.new(initial_params[:city], initial_params[:state])
    vacation_params[:name] = initial_params[:name]
    vacation_params[:city] = initial_params[:city]
    vacation_params[:state] = initial_params[:state]
    vacation_params[:country] = initial_params[:country]
    vacation_params[:start_date] = initial_params[:start_date]
    vacation_params[:end_date] = initial_params[:end_date]
    # vacation_params[:latitude] = coordinates.get_coordinates[0]
    # vacation_params[:longitude] = coordinates.get_coordinates[1]
    # binding.pry
    vacation_params
  end

end

app/views/owner/vacations/show.html.erb
  <body class="bg" id="vacation">
  <% if facade.vacation.new_vacation? %>
  <section class="form-container">
    <h1 class="dark">Get Started!</h1>
    <%= button_to "Add an Activity", new_vacation_owner_activity_path(facade.vacation), method: :get, class: :btn %>
    <%= button_to "Invite Participants", owner_vacation_invite_path(facade.vacation), method: :get, class: :btn %>
  </section>
<% else %>
  <div class="vacation-header">
  <figure class="header-grid">
    <h1><%= facade.vacation_name %></h1>
  </figure>
  <figure class="header-grid-right">
    <h2 class="light">I'm Owed: <%= number_to_currency(facade.owed_balance(current_user)) %></h2>
  </figure>
  <figure class="header-grid-right">
    <h2 class="light">I Owe: <%= number_to_currency(facade.outstanding_balance(current_user)) %></h2>
    </figure>
  </div>
  <div class="vacation-container">
    <section class="subnav">
      <%= link_to "+ Add an Activity", new_vacation_owner_activity_path(facade.vacation)  %>
      <%= link_to "+ Invite Participants", owner_vacation_invite_path(facade.vacation) %>
     <%= link_to "Join the Chat!", vacation_messages_path(facade.vacation) %>
    </section>
    <h2><%= facade.vacation.start_date.strftime("%m/%d/%Y") %> - <%= facade.vacation.end_date.strftime("%m/%d/%Y") %></h2>
    <h4>Hosted By: <%= facade.vacation_host %></h4><br />
    <h4>Location: <%= facade.vacation.city %></h4>
    <h2>Activities:</h2>
    <section class="vacay-container">
      <% facade.all_activities.each do |activity| %>
        <% if activity.vacation_id == facade.vacation_id %>
          <div id="activity-<%= activity.id %>" class="vacay-item">
            <h2><%= link_to activity.name, vacation_owner_activity_path(facade.vacation_id, activity.id) %></h2>
            <li>Description: <%= activity.description %></li>
            <h3>Attending:</h3>
              <% activity.user_activities.each do |ua| %>
              <figure class="attendee">
                <%= ua.user_name %>
                <% if ua.activity.user_id != ua.user_id %>
                  <%= link_to "x", remove_vacation_owner_activity_path(facade.vacation, activity, user_id: ua.user_id), method: :patch %>
                <% end %>
              </figure>
              <% end %>
              <br/>
              <%= link_to "+ Invite Participants", new_owner_activity_user_activity_path(activity.id) %>
              <br>
              <% if facade.vacation.users.count > activity.user_activities.count %>
                <%= link_to "+ Invite All Vacationers", mass_invite_owner_activity_path(activity_id: activity), method: :patch %>
              <% end %>
              <% if activity.user_id != current_user.id && current_user.attending?(activity) && !facade.paid?(activity, current_user) %>
                <br /><br />
                <li>Price Per Person: <%= number_to_currency(facade.user_activity_price(activity, current_user)) %></li>
                <%= button_to "Settle Up", vacation_dwollas_transfer_path(activity_id: activity.id, vacation_id: facade.vacation_id), class: :button %>
              <% end %>
          </div>
          <% end %>
        <% end %>

      </section>
    </div>

  <% end %>
  </body>