config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/vacations', to: 'users/vacations#index', as: :vacations
  get '/dashboard', to: 'users#show', as: :dashboard

  get '/oauth', to: 'users/dwollas#create', as: :users_auth

  namespace :users do
    resources :dwollas, only: [:create, :new]
    resources :funding_sources, only: [:new]
    resources :vacations, only: [:create, :new, :show, :index] do
      resources :activities, only: [:show, :new, :create]
    end
    resources :activities, only: [] do
      resources :user_activities, only: [:create, :destroy]
    end
  end

  get '/update_funding_source', to: 'users#update'

  resources :vacations do
    namespace :owner do
      resources :activities do
        member {patch :remove}
      end
    end

  post '/transfer', to: 'users/dwollas#transfer', as: :dwollas_transfer
  end

  resources :users, only: [:new, :create, :update]

  namespace :owner do
    resources :vacations, only: [:show] do
      get '/invite', to: 'invitations#new'
      post '/invite', to: 'invitations#create'
    end
    resources :activities, only: [] do
      member {patch :mass_invite}
      resources :user_activities, only: [:create, :new]
    end
  end

  get '/vacation/:id/messages', to: 'messages#index', as: :vacation_messages
  post '/vacation/:id/messages', to: 'messages#create'
  # resources :messages, only: [:index, :create]

  mount ActionCable.server, at: '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_activities
  has_many :activities, through: :user_activities
  has_many :vacation_users
  has_many :vacations, through: :vacation_users
  has_many :messages
  NAME_REGEX = /\w+/

  validates_uniqueness_of :email
  validates_presence_of :first_name, :last_name, :email
  has_secure_password

  def self.check_for_existing_users(owner, email_array, vacay_id)
    non_existent_users = []
    email_array.each do |email|
      if User.find_by(email: email) == nil
        non_existent_users << email
      else
        self.add_existing_user(owner, email, vacay_id)
      end
    end
    non_existent_users
  end

  def self.add_existing_user(owner, email, vacay_id)
    NotificationMailer.notify(owner, email, vacay_id).deliver_now
    self.update_vacation_user_table(email, vacay_id)
  end

  def self.update_vacation_user_table(email, vacay_id)
    user = User.find_by(email: email)
    VacationUser.create(user_id: user.id, vacation_id: vacay_id)
  end

  def attending?(activity)
    activity.user_activities.any? do |ua|
      ua.user_id == self.id
    end
  end
end

app/models/vacation.rb
class Vacation < ApplicationRecord
  has_many :activities
  has_many :vacation_users
  has_many :users, through: :vacation_users
  has_many :messages

  validates_presence_of :name,
                        :city,
                        :state,
                        :country,
                        :start_date,
                        :end_date

  def host
    vacation_user = self.vacation_users.where(role: 1)[0]
    User.find(vacation_user.user_id)
  end

  def new_vacation?
    self.activities.count == 0
  end

  def calculate_balance(user)
    find_activities(user)
    .where(user_id: user.id)
    .where.not('activities.user_id' => user.id)
    .sum(:price)
  end

  def find_activities(user)
    UserActivity
    .joins(:activity)
    .where(paid: false)
    .where('activities.vacation_id' => self.id)
  end

  def calculate_owed_balance(user)
    find_activities(user)
    .where('activities.user_id' => user.id)
    .sum(:price)
  end

  def owner?(user)
    self.vacation_users.any? do |vu|
      vu.user_id == user.id && vu.vacation_id == self.id && vu.role == 1
    end
  end
end

app/controllers/owner/vacations_controller.rb
class Owner::VacationsController < ApplicationController

  def show
    if Vacation.find(params[:id]).host == current_user
      destination = Vacation.find(params[:id])
      # @locations = [[destination.city, destination.latitude, destination.longitude]]
      # @key = ENV['google_key']
      render locals: {
        facade: VacationsFacade.new(params[:id])
      }
    else render file: "#{Rails.root}/public/404.html" , status: 404
    end
  end

end

app/controllers/users/activities_controller.rb
class Users::ActivitiesController < ApplicationController

  def index

  end

  def show
    render locals: {
      facade: ActivityFacade.new(params[:id])
    }
  end

  def new
    @vacation = Vacation.find(params[:vacation_id])
    @activity = Activity.new
  end

  def create
    @vacation = Vacation.find(params[:vacation_id])
    @activity = @vacation.activities.new(activity_params)
    if @activity.save
      UserActivity.create(user_id: current_user.id, quantity: 1, price: @activity.price_calculation, paid: true, activity_id: @activity.id)
      if @vacation.host == current_user
        redirect_to owner_vacation_path(@vacation)
      else
        redirect_to users_vacation_path(@vacation)
      end
    else
      render :new
    end
  end

  private

  def activity_params
    params.require(:activity).permit([:name, :description, :price, :cutoff_date, :no_of_days, :type]).merge(user_id: current_user.id, vacation_id: @vacation.id)
  end
end

app/controllers/users/dwollas_controller.rb
class Users::DwollasController < ApplicationController
  def new
  end

  def create
    token = dwolla_token
    response = dwolla_customer_location(token)
    current_user.update(dwolla_id: response.response_headers[:location])
    flash[:success] = "You've connected Dwolla to VacayPay."
    redirect_to dashboard_path
  end

  def transfer
    token = dwolla_token
    response = dwolla_transfer(token)
    activity = UserActivity.find_by(activity_id: params[:activity_id], user_id: current_user.id)
    activity.update(paid: true)
    activity = Activity.find(params[:activity_id])
    flash[:success] = "You successfully paid for #{activity.name}."
    if vacation_owner?
      redirect_to owner_vacation_path(activity.vacation)
    else
      redirect_to users_vacation_path(activity.vacation)
    end
  end

  private

  def dwolla_customer_location(token)
    @_customer_location ||= dwolla_customer_service(token).create_verified_user
  end

  def dwolla_token
    @_dwolla_token ||= dwolla_oauth_service.application_token
  end

  def dwolla_oauth_service
    @_oauth_service ||= DwollaOauthService.new
  end

  def dwolla_customer_service(token)
    @_customer_service ||= DwollaCustomerService.new(current_user, user_params, token)
  end

  def dwolla_transfer_service(token)
    activity = Activity.find(params[:activity_id])
    source = current_user.dwolla_funding_source
    destination = User.find(activity.user_id).dwolla_funding_source
    user_activity = UserActivity.find_by(activity_id: params[:activity_id], user_id: current_user.id)
    @_transfer_service ||= DwollaTransferService.new(source, destination, user_activity, token)
  end

  def dwolla_transfer(token)
    service = dwolla_transfer_service(token)
    service.create_transfer
  end

  def user_params
    params.permit(:address, :city, :state, :postal_code, :dob, :ssn)
  end
end

app/controllers/users/funding_sources_controller.rb
class Users::FundingSourcesController < ApplicationController
  def new
    @iav = DwollaFundingService.new
    @user = current_user
    @iav_token = @iav.get_iav_token(current_user)[:token]
  end
end

app/controllers/users/user_activities_controller.rb
class Users::UserActivitiesController < ApplicationController

  def create
    associated_activity.increment!(:num_attendees)
    UserActivity.create(user_id: current_user.id, quantity: 1, price: associated_activity.price_calculation, paid: false, activity_id: associated_activity.id)
    redirect_to users_vacation_activity_path(associated_activity.vacation, associated_activity)
  end

  def destroy
    associated_activity.decrement!(:num_attendees)
    user_activity = UserActivity.where(activity_id: associated_activity.id).find_by(user_id: current_user.id)
    user_activity.delete
    if associated_activity.vacation.vacation_users.where(role: 1)[0].user_id == current_user.id
      redirect_to vacation_owner_activity_path(associated_activity.vacation, associated_activity)
    else
      redirect_to users_vacation_activity_path(associated_activity.vacation, associated_activity)
    end
  end

  private

  def associated_activity
    Activity.find(params[:activity_id])
  end

end

app/controllers/users/vacations_controller.rb
class Users::VacationsController < ApplicationController

  def index

  end

  def show
    destination = Vacation.find(params[:id])
    # @locations = [[destination.city, destination.latitude, destination.longitude]]
    # @key = ENV['google_key']
    render locals: {
      facade: VacationsFacade.new(params[:id])
    }
  end

  def new
    @vacation = Vacation.new
  end

  def create
    @vacation = Vacation.new(vacation_params)
    if @vacation.save
      current_user.vacation_users.create(role: 1, vacation: @vacation)
      flash[:success] = "#{@vacation.name} has been created!"
      redirect_to owner_vacation_path(@vacation)
    else
      render :new
    end
  end


  private

  def initial_params
    params.require(:vacation).permit(:name, :city, :state, :country, :start_date, :end_date)
  end

  def vacation_params
    vacation_params = {}
    # coordinates = GeoFacade.new(initial_params[:city], initial_params[:state])
    vacation_params[:name] = initial_params[:name]
    vacation_params[:city] = initial_params[:city]
    vacation_params[:state] = initial_params[:state]
    vacation_params[:country] = initial_params[:country]
    vacation_params[:start_date] = initial_params[:start_date]
    vacation_params[:end_date] = initial_params[:end_date]
    # vacation_params[:latitude] = coordinates.get_coordinates[0]
    # vacation_params[:longitude] = coordinates.get_coordinates[1]
    # binding.pry
    vacation_params
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for registering, you are now logged in as #{@user.email}!"
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def update
    @iav = DwollaFundingService.new
    current_user.update!(dwolla_funding_source: @iav.get_funding_source(current_user))
    flash[:success] = "You've connected your bank account."
    redirect_to dashboard_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/views/users/vacations/index.html.erb
<body class="bg" id="index">
  <% if current_user.vacations.empty? %>
  <section class="form-container">
    <br />
    <h1 class="dark">You do not have any upcoming vacations.</h1>
    <%= button_to "Create a Vacation", new_users_vacation_path, method: :get, class: :btn  %>
    <br />
    </section>
  <% else %>
  <section class="upcoming-vacations">
    <h1>Upcoming Vacations</h1>
    <section class="vacay-container">
      <% current_user.vacations.each do |vacation| %>
        <figure class="vacay-item">
          <div id="vacation-<%= vacation.id %>">

          <% if vacation.owner?(current_user) %>
            <h2><%= link_to vacation.name, owner_vacation_path(vacation) %>:</h2>
          <% else %>
            <h2><%= link_to vacation.name, users_vacation_path(vacation) %>:</h2>
          <% end %>

          <h3><%= vacation.start_date.strftime("%m/%d/%Y") %> - <%= vacation.end_date.strftime("%m/%d/%Y") %></h3>
          <li>Location: <%= vacation.city %>, <%= vacation.state %></li>
          <li>Hosted By: <%= vacation.host.first_name %></li>
          <li>I Owe: <%= number_to_currency(vacation.calculate_balance(current_user)) %></li>
          <li>I'm Owed: <%= number_to_currency(vacation.calculate_owed_balance(current_user)) %></li>

          <% if vacation.owner?(current_user) %>
            <%= button_to "View Vacation", owner_vacation_path(vacation), method: :get, class: :button %>
          <% else %>
            <%= button_to "View Vacation", users_vacation_path(vacation), method: :get, class: :button %>
          <% end %>
          </div>
        </figure>
      <% end %>
    </section>
  </section>
  <% end %>
</body>

app/views/users/vacations/new.html.erb
<body class="bg" id="form">
  <div class="form-container">
    <h1 class="dark">Create a New Vacation</h1>
    <% if @vacation.errors.any? %>
      <ul class="errors">
        <% @vacation.errors.full_messages.each do |message| %>
          <li class="error"><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_for [:users, @vacation], action: :create do |f| %>
      <p><%= f.label :name %><br />
      <%= f.text_field :name %></p>

      <p><%= f.label :city %><br />
      <%= f.text_field :city %></p>

      <p><%= f.label :state %><br />
      <%= f.text_field :state %></p>

      <p><%= f.label :country %><br />
      <%= f.text_field :country %></p>

      <p><%= f.label :start_date %><br />
      <%= f.date_field :start_date %></p>

      <p><%= f.label :end_date %><br />
      <%= f.date_field :end_date %></p>

      <p><%= f.submit "Create Vacation", class: :btn %></p>
    <% end %>
  </div>
</body>

app/views/users/vacations/show.html.erb
<body class="bg" id="vacation">
  <div class="vacation-header">
  <figure class="header-grid">
    <h1><%= facade.vacation_name %></h1>
  </figure>
  <figure class="header-grid-right">
    <h2 class="light">I'm Owed: <%= number_to_currency(facade.owed_balance(current_user)) %></h2>
  </figure>
  <figure class="header-grid-right">
    <h2 class="light">I Owe: <%= number_to_currency(facade.outstanding_balance(current_user)) %></h2>
    </figure>
  </div>
  <div class="vacation-container">
  <section class="subnav">
    <%= link_to "+ Add an Activity", new_users_vacation_activity_path(facade.vacation) %>
    <%= link_to "Join the Chat!", vacation_messages_path(facade.vacation) %>
  </section>


    <h2><%= facade.vacation.start_date.strftime("%m/%d/%Y") %> - <%= facade.vacation.end_date.strftime("%m/%d/%Y") %></h2>
    <h4>Hosted By: <%= facade.vacation_host %></h4><br />
    <h4>Location: <%= facade.vacation.city %></h4><br /><Br />
    <h2>My Activities:</h2>
    <section class="vacay-container">
      <% facade.attending_activities(current_user).each do |activity| %>
        <% if activity.vacation_id == facade.vacation_id %>
          <div id="activity-<%= activity.id %>" class="vacay-item">
            <% if activity.user_id == current_user.id %>
              <h2><%= link_to activity.name, vacation_owner_activity_path(facade.vacation_id, activity.id) %></h2>
            <% else %>
              <h2><%= link_to activity.name, users_vacation_activity_path(facade.vacation_id, activity.id) %></h2>
            <% end %>
            <li>Description: <%= activity.description %></li>
            <li>Price Per Person: <%= number_to_currency(facade.user_activity_price(activity, current_user)) %></li>
            <% if current_user.id == activity.user_id %>
              <%= link_to "+ Invite Participants", new_owner_activity_user_activity_path(activity.id) %>
              <br>
              <% if facade.vacation.users.count > activity.user_activities.count %>
                <%= link_to "+ Invite All Vacationers", mass_invite_owner_activity_path(activity_id: activity), method: :patch %>
              <% end %>
            <% else %>
              <% if facade.paid?(activity, current_user) %>
                PAID
              <% else %>
                <%= button_to "Settle Up", vacation_dwollas_transfer_path(activity_id: activity.id, vacation_id: facade.vacation_id), class: :button %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </section>

    <h2>Join Activities:</h2>
    <% facade.non_attending_activities(current_user).each do |activity| %>
      <% if activity.vacation_id == facade.vacation_id %>
        <div id="activity-<%= activity.id %>" class="vacay-item">
          <h2><%= activity.name %></h2>
          <li>Description: <%= activity.description %></li>
          <li>Price Per Person: <%= number_to_currency(activity.price) %></li>
          <%= button_to "Join Activity", users_activity_user_activities_path(activity), class: :button %>
        </div>
      <% end %>
    <% end %>
    <section class="vacay-container">

    </section>
  </div>
</body>